name: SiPandu
description: Rehandling SuperApps
publish_to: "none"
version: 1.0.0+2
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  intl: ^0.18.1
  google_fonts: ^6.2.1
  material_design_icons_flutter: ^7.0.7296
  file_picker: ^8.0.3
  # uuid: ^4.4.0
  cached_network_image: ^3.3.1
  permission_handler: ^11.3.1
  geolocator: ^12.0.0
  flutter_map: ^6.1.0
  carousel_slider: ^4.1.1
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.2.4
  blur: ^3.1.0
  # flutter_svg: ^2.0.5
  custom_clippers: ^2.0.0
  badges: ^3.1.1
  flutter_markdown: ^0.7.1
  # dotted_border: ^2.0.0+3
  # faker_dart: ^0.2.2
  # syncfusion_flutter_charts: ^25.2.7
  qr_flutter: ^4.1.0
  path_provider: ^2.1.3
  flutter_animate: ^4.1.1+1
  dio: ^5.0.1
  flutter_staggered_grid_view: ^0.7.0
  formz: ^0.7.0
  sentry_flutter: ^8.2.0
  # m7_livelyness_detection: ^0.0.6+4
  # m7_livelyness_detection:
  #   git:
  #     url: https://github.com/fahiem152/m7_livelyness_detection.git
  #     ref: master # commit hash
  # talker_flutter: ^4.2.3
  shared_preferences: ^2.2.2
  # talker_dio_logger: ^4.2.3
  # graphql_flutter: ^5.1.2
  flutter_editable_table: ^1.1.2
  image_picker: ^1.0.4
  camera: ^0.11.0+1
  image_watermark: ^0.1.0
  flutter_image_edit_watermark: ^0.0.2
  # mobile_scanner: ^5.1.1
  get_it: ^7.6.7
  internet_connection_checker: ^1.0.0+1
  pdf: ^3.8.4
  open_file_plus: ^3.4.1
  webview_flutter: ^4.4.4
  # device_info_plus: ^10.1.0
  flutter_background_service: ^5.0.5
  workmanager: ^0.5.2
  web_socket_channel: ^2.4.0
  image_picker_web: ^4.0.0
  # esc_pos_utils_plus: ^2.0.1+6
  # print_bluetooth_thermal: ^1.1.0
  get: ^4.6.6
  connectivity_plus: ^5.0.2
  flutter_custom_clippers: ^2.1.0
  signature: ^5.1.0
  flutter_exif_rotation: ^0.5.1
  shimmer: ^3.0.0
  awesome_dialog: ^3.2.1
  lottie: ^3.0.0
  package_info_plus: ^8.0.0
  printing: ^5.12.0
  open_file: ^3.3.2
  jwt_decoder: ^2.0.1
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  firebase_core: ^3.1.1
  # awesome_notifications: ^0.7.7
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_messaging: ^15.0.2
  flutter_local_notifications: ^17.2.1
  flutter_launcher_icons: ^0.13.1
#   awesome_notifications_fcm: ^0.7.3
# awesome_notifications_fcm:
#   ^0.9.3+1
# stamp_image: ^0.0.2
# image: ^4.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/
    - assets/fonts/noto-sans.ttf
    - assets/animation/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/rehandling.png"
