name: hyper_ui
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  intl: ^0.18.1
  google_fonts: ^4.0.4
  material_design_icons_flutter: ^7.0.7296
  file_picker: ^5.2.2
  uuid: ^3.0.6
  flutter_image_compress: ^2.0.3
  cached_network_image: ^3.3.1
  permission_handler: ^10.4.5
  geolocator: ^9.0.2
  flutter_map: ^4.0.0
  carousel_slider: ^4.1.1
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.2.4
  blur: ^3.1.0
  flutter_svg: ^2.0.5
  custom_clippers: ^2.0.0
  badges: ^3.1.1
  flutter_markdown: ^0.6.12
  dotted_border: ^2.0.0+3
  faker_dart: ^0.1.11
  syncfusion_flutter_charts: ^21.2.4
  qr_flutter: ^4.1.0
  path_provider: ^2.0.11
  flutter_animate: ^4.1.1+1
  dio: ^5.0.1
  flutter_staggered_grid_view: ^0.6.2
  formz: ^0.6.0
  sentry_flutter: ^7.10.1
  # m7_livelyness_detection: ^0.0.6+4
  # m7_livelyness_detection:
  #   git:
  #     url: https://github.com/fahiem152/m7_livelyness_detection.git
  #     ref: master # commit hash
  talker_flutter: ^3.4.0
  shared_preferences: ^2.2.2
  talker_dio_logger: ^2.3.0
  graphql_flutter: ^5.1.2
  flutter_editable_table: ^1.1.2
  image_picker: ^1.0.4
  camera: ^0.10.5+5
  image_watermark: ^0.0.5
  flutter_image_edit_watermark: ^0.0.2
  mobile_scanner: ^3.5.6
  get_it: ^7.6.7
  internet_connection_checker: ^1.0.0+1
  pdf: ^3.8.4
  syncfusion_flutter_pdf: ^21.2.10
  open_file_plus: ^3.4.1
  webview_flutter: ^4.4.4
  device_info_plus: ^9.1.1
  flutter_background_service: ^5.0.5
  workmanager: ^0.5.2
  web_socket_channel: ^2.4.0
  image_picker_web: ^3.1.1
  esc_pos_utils_plus: ^2.0.1+6
  print_bluetooth_thermal: ^1.1.0
  get: ^4.6.6
  connectivity_plus: ^3.0.6
  flutter_custom_clippers: ^2.1.0
  # stamp_image: ^0.0.2
  # image: ^4.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  image_picker: ^1.0.4
flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/
    - assets/fonts/noto-sans.ttf
